# Doc site [title, and start page]
site:
  title: SUSE CaaS Platform Documentation
  start_page: suse-caasp::index

content:
  sources:
  # For building locally
  #- url: .
  # For building from the github repository directly.
  - url: https://github.com/SUSE/doc-caasp.git
    branches:
    - 'antora'

ui:
  bundle:
    url: ui-bundle.zip
    snapshot: false
  supplemental_files: ./supplemental-ui
output:
  dir: ./public
runtime:
  cache_dir: ./.cache/antora
